// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CredentialUIClient is the client API for CredentialUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialUIClient interface {
	// ListEngineSpecs returns a list of Credential Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CredentialUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type credentialUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialUIClient(cc grpc.ClientConnInterface) CredentialUIClient {
	return &credentialUIClient{cc}
}

func (c *credentialUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (CredentialUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CredentialUI_ServiceDesc.Streams[0], "/v1.CredentialUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &credentialUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CredentialUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type credentialUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *credentialUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *credentialUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CredentialUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialUIServer is the server API for CredentialUI service.
// All implementations must embed UnimplementedCredentialUIServer
// for forward compatibility
type CredentialUIServer interface {
	// ListEngineSpecs returns a list of Credential Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, CredentialUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCredentialUIServer()
}

// UnimplementedCredentialUIServer must be embedded to have forward compatible implementations.
type UnimplementedCredentialUIServer struct {
}

func (UnimplementedCredentialUIServer) ListEngineSpecs(*ListEngineSpecsRequest, CredentialUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedCredentialUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCredentialUIServer) mustEmbedUnimplementedCredentialUIServer() {}

// UnsafeCredentialUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialUIServer will
// result in compilation errors.
type UnsafeCredentialUIServer interface {
	mustEmbedUnimplementedCredentialUIServer()
}

func RegisterCredentialUIServer(s grpc.ServiceRegistrar, srv CredentialUIServer) {
	s.RegisterService(&CredentialUI_ServiceDesc, srv)
}

func _CredentialUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CredentialUIServer).ListEngineSpecs(m, &credentialUIListEngineSpecsServer{stream})
}

type CredentialUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type credentialUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *credentialUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CredentialUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CredentialUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialUI_ServiceDesc is the grpc.ServiceDesc for CredentialUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CredentialUI",
	HandlerType: (*CredentialUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CredentialUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _CredentialUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "credential-ui.proto",
}
